### ISSUE TITLE
Segfault when output directory does not exist

### ISSUE THREAD

**Issue by brantfaircloth** [dfguan/pin_hic#4]
Hi Dengfeng,

Thank you for your work on this scaffolding approach and software!  I'm excited to see the results.

I wanted to mention that I ran into a segfault when running `pin_hic_it` for the first time because I (mistakenly) assumed the output directory would be created when the code was run.  I took a look at the core dump and read back through the README, and it became reasonably clear to me that an existing directory was a pre-requisite... but, that initial segfault was not the expected behavior.  So, maybe just mentioning this in case anyone runs into the same issue.

Thanks again for your work!
-brant

**Comment by dfguan** [comment]
Hey brant, 

Thanks for trying pin_hic and the suggestion, I have updated the code now it will pop out an error when output directory is not found.  Also pin_hic is not tested on many species so far, not for sure how well it can perform. I would be good if you can give me some feedbacks about the scaffolding results. I will take some time, see if i can improve it. 

Best, 

Dengfeng.

**Comment by minalj365** [comment]
Hi there!

Thanks for addressing this issue. I am running into the same issue with pin_hic_it. I give output directory and still get segfault. Attaching the log file here for you to check. 

Thanks,
Minal

[pin_hic.log](https://github.com/dfguan/pin_hic/files/7770634/pin_hic.log)
